# Copyright (c) 2023 Ferrous Systems
# SPDX-License-Identifier: MIT OR Apache-2.0

name: workflow-build-everything-ferrocene
run-name: Build Everything with Ferrocene
on: [push, pull_request]
jobs:
  job-build-demo-app:
    runs-on: ubuntu-latest
    steps:
      - name: Install Arm C compiler
        run: |
          sudo apt-get update -y && sudo apt-get -y install gcc-arm-none-eabi
          curl --proto '=https' --tlsv1.2 -LsSf https://github.com/ferrocene/criticalup/releases/download/v1.0.1/criticalup-installer.sh | sh
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Install Ferrocene
        env:
          CRITICALUP_TOKEN: ${{ secrets.CRITICALUP_TOKEN }}
        run: |
          criticalup install
          echo "$HOME/.local/share/criticalup/bin" >> $GITHUB_PATH
      - name: Find slug name
        run: |
          slug=$(./describe.sh "${GITHUB_REF}")
          echo "Building with slug '${slug}'"
          echo "BUILD_SLUG=${slug}" >> "${GITHUB_ENV}"
      - name: Check Demo App
        run: |
          cd demo-app
          rustc --version
          cargo --version
          cargo check --target=thumbv7em-none-eabi
      - name: Build Demo App
        run: |
          cd demo-app
          rustc --version
          cargo --version
          cargo build --target=thumbv7em-none-eabi --release
      - name: Upload demo-app
        uses: actions/upload-artifact@master
        with:
          name: demo-app
          path: demo-app/target/thumbv7em-none-eabi/release/demo-app
  job-build-threadx-sys:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Check threadx-sys
        run: |
          cd threadx-sys
          cargo check
      - name: Build threadx-sys
        run: |
          cd threadx-sys
          cargo build
